name: Build and Create Zip

on:
  workflow_dispatch:
    inputs:
      trigger-build:
        description: 'Trigger the build and zip creation'
        default: 'true'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Get Commit Hash and Branch Name and Create version.json
      id: commit_info
      run: |
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        echo '{ "CommitInformation": { "branch": "'$(git rev-parse --abbrev-ref HEAD)'", "commithash": "'$(git rev-parse --short HEAD)'" } }' > publish/version.json
        
    - name: Upload Artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
        path: publish/
        
          

